language: node_js

node_js:
  - 10
  - 9
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn lint
  - yarn build

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
