[build.environment]
  NODE_VERSION = "14.5.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--pure-lockfile --verbose"

[dev]
  framework = "#custom"
  command = "yarn dev"
  port = 8500
  publish = "public"
  targetPort = 8600
